In [4]:
#read in the iris data
from sklearn.datasets import load_iris
iris = load_iris()

#create X (features) and y (response)
X = iris.data
y = iris.target


In [5]:
#KNN with K=5
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X,y)
y_pred = knn.predict(X)


In [6]:
#method 1: use metrics module
from sklearn import metrics
print metrics.accuracy_score(y,y_pred)

0.966666666667


In [7]:
knn = KNeighborsClassifier(n_neighbors=1)
knn.fit(X,y)
y_pred = knn.predict(X)
print metrics.accuracy_score(y,y_pred)

1.0


In [9]:
#create X: 5 observations and 2 features
import numpy as np
X = np.arange(1,11).reshape((5,2))
print X

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [10]:
#create y: response vector of size 5
y = X.prod(axis = 1)
print y

[ 2 12 30 56 90]


In [11]:
#randomly split the rows of X into two pieces
from sklearn.cross_validation import train_test_split
X_split = train_test_split(X)
print X_split[0]
print X_split[1]

[[ 7  8]
 [ 1  2]
 [ 9 10]]
[[3 4]
 [5 6]]


In [12]:
# use random_state parameter to always get the same random split
X_split = train_test_split(X, random_state = 2)
print X_split[0]
print X_split[1]

[[3 4]
 [7 8]
 [1 2]]
[[ 5  6]
 [ 9 10]]


In [15]:
# "unpack" the list into two separate objects
X_train, X_test = train_test_split(X, random_state = 2)
print X_train
print X_test

[[3 4]
 [7 8]
 [1 2]]
[[ 5  6]
 [ 9 10]]


In [16]:
#randomly split the rows of X and y into two pieces
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=2)

In [17]:
# X has been split into two pieces
print X_train
print X_test

[[3 4]
 [7 8]
 [1 2]]
[[ 5  6]
 [ 9 10]]


In [18]:
# y has been split into two pieces with the same ordering
print y_train
print y_test

[12 56  2]
[30 90]


In [19]:
# Step 0: Load the iris data again
iris = load_iris()
X = iris.data
y = iris.target

In [20]:
# Step 1: split data into a training set and a testing set
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=4)
print X_train.shape
print X_test.shape
print y_train.shape
print y_test.shape

(112L, 4L)
(38L, 4L)
(112L,)
(38L,)


In [21]:
# Step 2: train the model on the training set (using K=1)
knn = KNeighborsClassifier(n_neighbors=1)
knn.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_neighbors=1, p=2, weights='uniform')

In [22]:
# Step 3: test the model on the testing set, and check the accuracy
y_pred = knn.predict(X_test)
print metrics.accuracy_score(y_test, y_pred)

0.947368421053


In [23]:
# Step 4: repeat this process for K=5
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)
print metrics.accuracy_score(y_test, y_pred)

0.973684210526


In [24]:
# train the model on X (not X_train) using k = 5
knn = KNeighborsClassifier(n_neighbors = 5)
knn.fit(X,y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_neighbors=5, p=2, weights='uniform')

In [25]:
# make a prediction for an unknown iris
out_of_sample = [5,4,3,2]
knn.predict(out_of_sample)

array([1])

In [30]:
# use a different random_state than last time
X_train, X_test, y_train, y_test = train_test_split(X,y,random_state = 1)
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)
print metrics.accuracy_score(y_test, y_pred)

1.0
